
CREATE TABLE FORMACAO (
                ID_FORMACAO BIGINT AUTO_INCREMENT NOT NULL,
                NOME VARCHAR(50) NOT NULL,
                PONTO BIGINT NOT NULL,
                PRIMARY KEY (ID_FORMACAO)
);


CREATE UNIQUE INDEX formacao_idx
 ON FORMACAO
 ( PONTO );

CREATE UNIQUE INDEX formacao_idx1
 ON FORMACAO
 ( NOME );

CREATE TABLE CURSO (
                ID_CURSO BIGINT AUTO_INCREMENT NOT NULL,
                NOME VARCHAR(50) NOT NULL,
                PRIMARY KEY (ID_CURSO)
);


CREATE UNIQUE INDEX curso_idx
 ON CURSO
 ( NOME );

CREATE TABLE PESSOA (
                ID_PESSOA BIGINT AUTO_INCREMENT NOT NULL,
                ID_CURSO BIGINT NOT NULL,
                NOME VARCHAR(50) NOT NULL,
                OBSERVACAO VARCHAR(1000),
                PRIMARY KEY (ID_PESSOA)
);


CREATE UNIQUE INDEX pessoa_idx
 ON PESSOA
 ( NOME );

CREATE TABLE PESSOA_FORMACAO (
                ID_FORMACAO BIGINT NOT NULL,
                ID_PESSOA BIGINT NOT NULL,
                PRIMARY KEY (ID_FORMACAO, ID_PESSOA)
);


ALTER TABLE PESSOA_FORMACAO ADD CONSTRAINT id_formacao_pessoa_formacao_fk
FOREIGN KEY (ID_FORMACAO)
REFERENCES FORMACAO (ID_FORMACAO)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE PESSOA ADD CONSTRAINT curso_pessoa_fk
FOREIGN KEY (ID_CURSO)
REFERENCES CURSO (ID_CURSO)
ON DELETE NO ACTION
ON UPDATE NO ACTION;

ALTER TABLE PESSOA_FORMACAO ADD CONSTRAINT pessoa_pessoa_formacao_fk
FOREIGN KEY (ID_PESSOA)
REFERENCES PESSOA (ID_PESSOA)
ON DELETE NO ACTION
ON UPDATE NO ACTION;